config/routes.rb
Rails.application.routes.draw do

  get 'proxy/get_commits/:group_id', controller: 'proxy', action: 'get_commits'

  root 'home#index'

  resources :tags, only: [:index, :show] do
    get 'resources', controller: 'resources', action: 'with_tag'
  end

  resources :resources

  resources :announcements

  namespace :admin do
    resources :users
  end

  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  resources :groups, only: [:index, :show]

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true, length: { minimum: 5 }
  validates :level, numericality: { only_integer: true, greater_than: 0, less_than: 3 }

  # after_create :send_by_email

  def send_by_email
    # Por el momento, simplemente iteraremos en todos
    # los usuarios... pero esto puede tardar harto si son
    # muchos usuarios... en ese caso necesitaríamos hacer
    # de esto una operación asíncrona (que se siga realizando
    # en background, sin necesidad de detener el flujo del programa principal)
    User.all.each do |u|
      AnnouncementMailer.send_announcement(self, u).deliver
    end
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        # TODO: lo más recomendable sería enviar el correo indirectamente
        # desde este punto, dándole a una clase la responsabilidad de crear
        # el anuncio y de realizar su envío por e-mail. Así, mantenemos
        # el controller simple y tampoco le entregamos al modelo AR responsabilidades
        # más allá de lo que realmente necesitamos de él.
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:title, :content, :level, :notify, :user_id)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :notify %><br>
    <%= f.check_box :notify %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<h1>Listing announcements</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Level</th>
      <th>Notify</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.title %></td>
        <td><%= announcement.content %></td>
        <td><%= announcement.level %></td>
        <td><%= announcement.notify %></td>
        <td><%= announcement.user %></td>
        <td><%= link_to 'Show', announcement %></td>
        <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
        <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Announcement', new_announcement_path %>

app/views/announcements/new.html.erb
<h1>New announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @announcement.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @announcement.content %>
</p>

<p>
  <strong>Level:</strong>
  <%= @announcement.level %>
</p>

<p>
  <strong>Notify:</strong>
  <%= @announcement.notify %>
</p>

<p>
  <strong>User:</strong>
  <%= @announcement.user %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>