config/routes.rb
Rails.application.routes.draw do

  get 'proxy/get_commits/:group_id', controller: 'proxy', action: 'get_commits'

  root 'home#index'

  resources :tags, only: [:index, :show] do
    get 'resources', controller: 'resources', action: 'with_tag'
  end

  resources :resources

  resources :announcements

  namespace :admin do
    resources :users
  end

  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  resources :groups, only: [:index, :show]

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true, length: { minimum: 5 }
  validates :level, numericality: { only_integer: true, greater_than: 0, less_than: 3 }

  # after_create :send_by_email

  def send_by_email
    # Por el momento, simplemente iteraremos en todos
    # los usuarios... pero esto puede tardar harto si son
    # muchos usuarios... en ese caso necesitaríamos hacer
    # de esto una operación asíncrona (que se siga realizando
    # en background, sin necesidad de detener el flujo del programa principal)
    User.all.each do |u|
      AnnouncementMailer.send_announcement(self, u).deliver
    end
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :project
  has_many :members, class: User
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tags

  has_attached_file :file
  do_not_validate_attachment_file_type :file

  validates :name, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :resources
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :group
  
  has_secure_password

  validates :first_name, presence: true, length: { in: 2..50 }
  validates :last_name, presence: true, length: { in: 2..50 }
  validates :email, presence: true, format: /\A[a-z0-9]+[a-z0-9\._-]*@[a-z0-9\.]+\.[a-z]{2,5}\z/i, uniqueness: true

  def complete_name
    [first_name, last_name].join(' ')
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/proxy_controller.rb
class ProxyController < ApplicationController
  def get_commits
    g = Group.find(params[:group_id])
    uri = URI("https://api.github.com/repos/#{g.git_repo}/commits")
    r = Net::HTTP.get(uri)
    r = JSON.parse(r)
    render json: r
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # TODO: momentáneo...
    @user.role = "student"
    if @user.save
      redirect_to root_path, notice: "Cuenta creada exitosamente."
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/proxy_helper.rb
module ProxyHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teachrapp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="login-bar">
      <% if current_user? %>
        Bienvenido(a), <%= current_user.first_name %>
        <%= link_to "Logout", session_path, method: :delete %>
      <% else %>
        <%= link_to "Login", new_session_path %>
      <% end %>
    </div>

    <% if flash.notice %>
      <div class="notice">
        <%= flash.notice %>
      </div>
    <% end %>
    <% if flash.alert %>
      <div class="alert">
        <%= flash.alert %>
      </div>
    <% end %>

    <div id="content">
      <%= yield %>
    </div>

    <footer>
      <hr>
      TeachrApp, Todos los derechos reservados &copy; 2014
    </footer>

  </body>
</html>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.file_field :file %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/_resources_list.html.erb
<% @resources.each do |resource| %>
  <div class="resource">
    <%= link_to image_tag('file.png'), resource %>
    <span>
      <%= link_to resource.name, resource %>
    </span>
    <span>
      <%= resource.user.first_name %>
    </span>
    <div class="tags">
      <%= render 'tags', tags: resource.tags %>
    </div>
    <div class="actions">
      <%= link_to "Editar", edit_resource_path(resource) %>
      <%= link_to "Eliminar", resource_path(resource), method: :delete %>
    </div>
  </div>
<% end %>

app/views/resources/_tags.html.erb
<ul class="tag-list">
  <% tags.each do |tag| %>
    <li><%= link_to tag.name, tag_resources_path(tag) %></li>
  <% end %>
</ul>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1><%= @resources_title || 'Todos los recursos' %></h1>
<p class="order-links">
  Ordenar por:
  <%= link_to 'nombre', resources_path(order: :name), remote: true, data: { type: 'html' } %>
  |
  <%= link_to 'creación', resources_path(order: :created_at), remote: true, data: { type: 'html' } %>
</p>
<div class="resources">
  <%= render partial: 'resources_list' %>
</div>

<%= link_to 'Crear Recurso', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @resource.description %>
</p>

<p>
  <strong>File:</strong>
  <%= link_to "Descargar", @resource.file.try(:url) %>
</p>

<p>
  <strong>Url:</strong>
  <%= @resource.url %>
</p>

<p>
  <strong>User:</strong>
  <%= @resource.user %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>